environment:
  node_pre_gyp_accessKeyId:
    secure: 7DrSVc5eIGtmMcki5H+iRft+Tk3MJTwDBQEUuJHWaQ4=
  node_pre_gyp_secretAccessKey:
    secure: 1amwJJw9fu0j6dXnc5KsAQbSYf7Cjw/dapT6OZWABa6nc52grkKeLQ+DGaOfQz8i
  matrix:
    - nodejs_version: 0.12.7
      platform: x86
      msvs_toolset: 12
      nwjs: 0.10.0
  access_token:
      secure: 58a9cd2232c05da94b829f4a139d4d99e662be65

install:
  # add local node to path (since we install it for msvs_toolset == 14)
  - SET PATH=%CD%;%PATH%;
  # add local node-pre-gyp dir to path
  - SET PATH=node_modules\.bin;%PATH%
  # install node version per visual studio toolset
  - powershell Update-NodeJsInstallation $env:nodejs_version $env:platform
  # clear out node-gyp header cache
  - SET PATH=C:\Program Files (x86)\MSBuild\%msvs_toolset%.0\bin;%PATH%
  - SET PATH=C:\Program Files (x86)\Microsoft Visual Studio %msvs_toolset%.0\VC\bin;%PATH%
  - if %platform% == x86 CALL "C:\Program Files (x86)\Microsoft Visual Studio %msvs_toolset%.0\VC\vcvarsall.bat" amd64_x86
  - npm install nw-gyp -g
  - npm install --build-from-source --runtime=node-webkit --target_arch=ia32 --target=%nwjs%

artifacts:
  - path: '**\*.node'
    name: sqlitebuild

on_success:
#  - git config --global user.email "cwpro.pg@gmail.com"
#  - git config --global user.name "alejandronunez"
#  - git config --global push.default simple
#  - git add lib/binding/node-webkit-v0.10.0-win32-ia32\node_sqlite3.node
#  - git commit -m "automatic"
#  - git remote -v
#  - git config remote.origin.url https://alejandronunez:Ale880514@github.com/alejandronunez/dependstester.git
#  - git remote -v
#  - git push origin master

build: OFF
test: OFF

deploy:

- provider: GitHub
  tag: dependtesev-01
  auth_token:
    secure: jbwe6kvA2dFajNuhaN6igxsrzc74PLZF67j8yARmKt8L8+mHqcTy5TA5xLhSEFI/
  artifact: sqlitebuild
  draft: true
